name: YUMII
favicon: null
layout_spectrum: 0.6017
typography_spectrum: 0.4669066141359508
title: YUMII PHOTOGRAPHY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0021'
    - '#c3c0ff'
    - '#f372ca'
    - '#cbffee'
    - '#c30054'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.731064434396103
purpose: []
